Class {
	#name : #BlNullHostSurfaceRenderer,
	#superclass : #BlHostSurfaceRenderer,
	#category : #'BlocBenchs-FPS-Host-NullRenderer'
}

{ #category : #initialization }
BlNullHostSurfaceRenderer >> initializeForSurface: aSurface [
	
	"Nothing"
]

{ #category : #rendering }
BlNullHostSurfaceRenderer >> renderSurface: aSurface damaged: aCollectionOfRectangles [
	"Render a given surface on a host space"

	
]
