Trait {
	#name : #TBlBNestedTransformationsLogic,
	#category : #'BlocBenchs-Benchs'
}

{ #category : #accessing }
TBlBNestedTransformationsLogic >> figureExtent [

	^ 600.0 asPoint
]

{ #category : #hook }
TBlBNestedTransformationsLogic >> figureOffset [

	^ 50.0 asPoint
]

{ #category : #accessing }
TBlBNestedTransformationsLogic >> logicalExtent [

	^ 750 @ 750
]

{ #category : #accessing }
TBlBNestedTransformationsLogic >> numberOfFigures [

	^ 50
]

{ #category : #accessing }
TBlBNestedTransformationsLogic >> targetRelativeRotation [

	^ 5.0
]

{ #category : #accessing }
TBlBNestedTransformationsLogic >> targetRelativeScale [

	^ 0.9
]
