Extension { #name : #BlTextAttribute }

{ #category : #'*BlocBenchs-PCRenderer' }
BlTextAttribute >> pureCairoDrawAboveOn: aPCCanvas with: aBlTextParagraphSpan [
	"Attribute may add additional visual effects above the text"
]

{ #category : #'*BlocBenchs-PCRenderer' }
BlTextAttribute >> pureCairoDrawBelowOn: aPCCanvas with: aBlTextParagraphSpan [
	"Attribute may add additional visual effects below the text"
]
